---
tt_config_files:
  - "{{ playbook_dir }}/elements/base.conf.j2"
  - "{{ playbook_dir }}/elements/vm.conf.j2"
  - "{{ playbook_dir }}/elements/floating.conf.j2"
  - "{{ playbook_dir }}/elements/ceph.conf.j2"
  - "{{ playbook_dir }}/elements/volume.conf.j2"
  - "{{ playbook_dir }}/elements/openstack-version-ussuri.conf.j2"
  - "{{ playbook_dir }}/elements/overrides.conf.j2"

overrides_free_form_extras: |
  [compute]
  flavor_ref = f570697a-a99b-4688-8ad2-8bb1f8190d6e
  flavor_ref_alt = 6c2c32d7-ab7a-40fd-918d-6b553d4d4f7e
  [compute-feature-enabled]
  resize = true
  block_migration_for_live_migration = true
  volume_backed_live_migration = true
  [identity-feature-enabled]
  domain_specific_drivers = true
  immutable_user_source = true
  [network-feature-enabled]
  ipv6 = false
  api_extensions = address-scope,allowed-address-pairs,auto-allocated-topology,availability_zone,availability_zone_filter,default-subnetpools,dns-integration,empty-string-filtering,external-net,extra_dhcp_opt,extraroute,fip-port-details,flavors,ip-substring-filtering,router,ext-gw-mode,multi-provider,net-mtu,net-mtu-writable,network_availability_zone,network-ip-availability,pagination,port-mac-address-regenerate,binding,binding-extended,port-security,project-id,provider,quotas,quota_details,rbac-policies,rbac-address-scope,rbac-security-groups,rbac-subnetpool,revision-if-match,standard-attr-revisions,router_availability_zone,port-security-groups-filtering,security-group,service-type,sorting,standard-attr-description,stateful-security-group,subnet_onboard,subnet-service-types,subnet_allocation,subnetpool-prefix-ops,standard-attr-tag,standard-attr-timestamp
  port_security = true
  [service_available]
  neutron = true
  swift = false
  [volume-feature-enabled]
  backup = false
  manage_volume = true
  

tt_output_file: "{{ playbook_dir }}/../config/tempest.conf"

# floating.conf.j2
public_network_id: 80231a21-7546-4fd8-944f-e619de5a3850
floating_network_name: external
