---
tt_config_files:
  - "{{ playbook_dir }}/elements/base.conf.j2"
  - "{{ playbook_dir }}/elements/vm.conf.j2"
  - "{{ playbook_dir }}/elements/floating.conf.j2"
  - "{{ playbook_dir }}/elements/ceph.conf.j2"
  - "{{ playbook_dir }}/elements/volume.conf.j2"
  - "{{ playbook_dir }}/elements/openstack-version-ussuri.conf.j2"
  - "{{ playbook_dir }}/elements/overrides.conf.j2"

overrides_free_form_extras: |
  [volume]
  build_timeout = 600
  [volume-feature-enabled]
  backup = False

tt_output_file: "{{ playbook_dir }}/../config/tempest.conf"

# floating.conf.j2
public_network_id: 80231a21-7546-4fd8-944f-e619de5a3850
floating_network_name: public
