---
tt_config_files:
  - "{{ playbook_dir }}/elements/base.conf.j2"
  - "{{ playbook_dir }}/elements/vm.conf.j2"
  - "{{ playbook_dir }}/elements/floating.conf.j2"
  - "{{ playbook_dir }}/elements/ceph.conf.j2"
  - "{{ playbook_dir }}/elements/volume.conf.j2"
  - "{{ playbook_dir }}/elements/openstack-version-ussuri.conf.j2"
  - "{{ playbook_dir }}/elements/overrides.conf.j2"

overrides_free_form_extras: |
  [compute]
  flavor_ref = 614e7815-e006-40b9-a0e6-e7399d069cd8
  flavor_ref_alt = f17c1bc0-d9dc-4756-ad91-80ad695059e4
  [identity-feature-enabled]
  domain_specific_drivers = true
  immutable_user_source = true
  [network-feature-enabled]
  api_extensions = address-scope,allowed-address-pairs,auto-allocated-topology,availability_zone,availability_zone_filter,default-subnetpools,dns-integration,empty-string-filtering,external-net,extra_dhcp_opt,extraroute,fip-port-details,flavors,ip-substring-filtering,router,ext-gw-mode,multi-provider,net-mtu,net-mtu-writable,network_availability_zone,network-ip-availability,pagination,port-mac-address-regenerate,binding,binding-extended,port-security,project-id,provider,quotas,quota_details,rbac-policies,rbac-address-scope,rbac-security-groups,rbac-subnetpool,revision-if-match,standard-attr-revisions,router_availability_zone,port-security-groups-filtering,security-group,service-type,sorting,standard-attr-description,stateful-security-group,subnet_onboard,subnet-service-types,subnet_allocation,subnetpool-prefix-ops,standard-attr-tag,standard-attr-timestamp
  port_security = true
  [service_available]
  neutron = true
  swift = false
  [volume-feature-enabled]
  backup = false
  

tt_output_file: "{{ playbook_dir }}/../config/tempest.conf"

# floating.conf.j2
public_network_id: addb7ab9-9732-4cd8-bbd6-bcf6825c4913
floating_network_name: external
